name: Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: üõí "Checkout Source code"
        
      - name: ‚ú® Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          version: 16.x
          cache: 'yarn'

      - name: üõ†Ô∏è Build
        run: |
          yarn install --frozen-lockfile
          npx cross-env NITRO_PRESET=netlify yarn build
        env:
          CI: true
          HUSKY: 0

      - name: Execute Tests
        run: yarn test

      - name: üöÄ Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "dist"
          production-branch: dev
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1